name: Deploy Website to S3 Bucket

on:
  push:
    branches:
      - 'main'
    paths:
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Copy website to S3
        run: aws s3 sync . s3://inventoryapp.rrc.ca --exclude "*" --include "index.html"
